# Generated by Django 4.0.3 on 2022-04-12 21:26

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('ubicacion', models.CharField(max_length=50)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=15)),
                ('habitaciones', models.IntegerField()),
                ('banos', models.IntegerField()),
                ('estacionamientos', models.IntegerField()),
                ('terreno', models.DecimalField(decimal_places=2, max_digits=10)),
                ('construccion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pisos', models.IntegerField()),
                ('operacion', models.CharField(choices=[('Venta', 'Venta'), ('Renta', 'Renta')], default='', max_length=10)),
                ('propiedad', models.CharField(choices=[('Cas', 'Casa'), ('Dep', 'Departamento'), ('Vil', 'Villa'), ('Res', 'Residencia'), ('Ofi', 'Oficina'), ('Ter', 'Terreno'), ('Bod', 'Bodega'), ('Des', 'Desarrollo'), ('Edi', 'Edificio')], default='', max_length=20)),
                ('imagen', models.ImageField(null=True, upload_to='propiedades')),
            ],
            bases=(models.Model, django.db.models.fields.DecimalField),
        ),
        migrations.CreateModel(
            name='imagenPropiedades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='propiedades')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Propiedades.properties')),
            ],
        ),
    ]
