# Generated by Django 4.0.3 on 2022-04-13 15:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Propiedades', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='properties',
            name='imagen',
        ),
        migrations.AddField(
            model_name='properties',
            name='moneda',
            field=models.CharField(choices=[('MXN', 'MXN'), ('USD', 'USD'), ('EUR', 'EUR')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='properties',
            name='slug',
            field=models.CharField(default=django.utils.timezone.now, max_length=250, verbose_name='Slug'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imagenpropiedades',
            name='propiedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='Propiedades.properties'),
        ),
    ]
