# Generated by Django 4.0.3 on 2022-04-13 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Propiedades', '0002_remove_properties_imagen_properties_moneda_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='slug',
            field=models.SlugField(max_length=250),
        ),
    ]
