# Generated by Django 4.0.3 on 2022-04-14 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Propiedades', '0003_alter_properties_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='propiedad',
            field=models.CharField(choices=[('Casa', 'Casa'), ('Departamento', 'Departamento'), ('Villa', 'Villa'), ('Residencia', 'Residencia'), ('Oficina', 'Oficina'), ('Terreno', 'Terreno'), ('Bodega', 'Bodega'), ('Desarrollo', 'Desarrollo'), ('Edificio', 'Edificio')], default='', max_length=20),
        ),
    ]
